### ISSUE TITLE
1.4 failing self tests

### ISSUE THREAD

**Issue by iankmor** [TRIQS/dft_tools#112]
A research group here asked me to install triqs and some applications including dft_tools so I downloaded the latest.  Both triqs and dft_tools compiled without errors and passed all self tests.

Then they decided they wanted version 1.4.2 of triqs which requires version 1.4 of dft_tools.  Both compiled without errors and triqs 1.4.2 passes all self tests but dft_tools 1.4 fails 3 of the 8 self tests:

   The following tests FAILED:
      1 - wien2k_convert (Failed)
      2 - hk_convert (Failed)
      6 - srvo3_transp (Failed)

The error from wien2k_convert and hk_convert is:

   TypeError: only integer scalar arrays can be converted to a scalar index

The error from srvo3_transp is:

   IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices 

Python version is 2.7.14; Numpy version is 1.13.3.

Do you know what might be causing those self tests to fail?

Thanks
Ian

**Comment by the-hampel** [comment]
Hi Ian, 
I vaguely remember having similar issues. I resolved it by using specific versions of numpy, scipy and hdf. I have a working docker container / file that should pass all tests. You can check the versions of each software in the Dockerfile: https://github.com/materialstheory/Dockerfiles/blob/master/triqs_legacy/Dockerfile . I think it was the version of scipy or hdf, because I am using the same version of numpy. Let me know if this helps. 

Best,
Alex

**Comment by iankmor** [comment]
Hi Alex

Starting from scratch, installing python in a separate tree with the same versions as your dockerfile and a fresh install of triqs and dft_tools, gets the same result: 3 of the 8 self tests fail.  I can't tell from your dockerfile what version of python is installed in your container.  We have 2.7.14. 

Thanks
Ian

**Comment by the-hampel** [comment]
Ah you are absolutely right! My tests failed with the same errors. I forgot to push the latest version of the dockerfile. I have to use numpy version **1.11.3**, since I found that the developers changed behavior of numpy in version 1.12. With this (even older) version all tests pass - which I also rechecked this morning. Please check the dockerfile again for the correct versions. 

I also added the tests in the make process of triqs. I think the python version that you have is fine, although I am using python 2.7.15rc1 . The rest of the setup can be found here: https://github.com/materialstheory/Dockerfiles/blob/master/base/base-bionic-gnu/Dockerfile . 

I hope this is really due to changes in numpy. At least I found some entries in the changelog, that they changed behavior specific to this issue.

Best,
Alex

**Comment by iankmor** [comment]
Hi Alex

It's working now with numpy 1.11.3.  Thanks your help.

Ian
