### ISSUE TITLE
key error in reading dictionary in wannier90converter

### ISSUE THREAD

**Issue by ghost** [TRIQS/dft_tools#121]
Hello, This is my first time learn TRIQS...

i have provided hr file and input file for wannier converter, but still, `Wannier90Converter` giving me error, no 'dim' dictionary found in `corr_shells` dict.

```
from triqs_dft_tools.converters import Wannier90Converter
>> Starting on 1 Nodes at : 2019-08-07 18:27:07.780396

Converter = Wannier90Converter(seedname='srvo3')
Converter.convert_dft_input()
>>Reading input from srvo3.inp...


KeyErrorTraceback (most recent call last)
<ipython-input-2-f7c938218daa> in <module>()
      1 Converter = Wannier90Converter(seedname='srvo3')
----> 2 Converter.convert_dft_input()

/usr/lib/python2.7/dist-packages/triqs_dft_tools/converters/wannier90_converter.py in convert_dft_input(self)
    167         # this is more general
    168         n_spin = SP + 1 - SO
--> 169         dim_corr_shells = sum([sh['dim'] for sh in corr_shells])
    170         mpi.report(
    171             "Total number of WFs expected in the correlated shells: %d" % dim_corr_shells)

KeyError: 'dim'

```
what happen? is this happen because different memory reference in core because mpi? how to configure the mpi if that's the case?

this is the input file `srvo3.inp` : 

```
 -1  8 8 8
 8.0
 4
 0 0 2 3 0 0
 1 0 2 3 0 0
 2 0 2 3 0 0
 3 0 2 3 0 0
```

**Comment by phibeck** [comment]
This error is related to the '-1' option that is supposedly determining the k-point mesh automatically. In this case you should not specify a k-point mesh (in this case 8 8 8), since these then end up in the following variables density_required, n_corr_shells etc...(to do: fix the error message)

So either use 0 with 8 8 8, or -1 and no specifications of the k-point mesh. This should work.

A more material-specific remark: Do you have SVO in a cubic or Pbnm-related structure? I'm guessing the first since you specified an homogeneous k-point grid. Then you would only need one line for one atom in the correlated shell. Also, SVO is d^1, so instead of 8 electrons you'd have 1 (or 4 in Pbnm). So for cubic try:
 0  8 8 8 (or just -1)
 1.0
 1
 0 0 2 3 0 0

In Pbnm-like structures, try:
 0  8 8 8 (or just -1)
 4.0
 4
 0 0 2 3 0 0
 1 0 2 3 0 0
 2 0 2 3 0 0
 3 0 2 3 0 0

I hope this solves it.

**Comment by ghost** [comment]
Wow, thank you. it works now! took 8 hours to run cthyb in my 4-cores laptop :)

And....

It seems that MaxEnt not included in triqs docker image. So i tried to install maxent manually from the container. The problem is, when compiling cmake the maxent, triqs uses cmake version 2.1.0. While in the image, the cmake version is 3.10.2, is it best for downgrade the cmake, or any solutions?

here the problem

```
triqs@0cbe525fa271:/home/environments/maxent.build$ sudo cmake ../maxent.src/
-- -------- BUILD-TYPE: Release -------------
-- Found TRIQSConfig.cmake with version 2.1.0, hash = e96f1d26217af753191482398dc568ac43aa920a
CMake Error at /usr/lib/cmake/triqs/TRIQSConfig.cmake:43 (message):
  For your own safety, you should use the same compiler as the one used to
  compile TRIQS !
Call Stack (most recent call first):
  CMakeLists.txt:33 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/environments/maxent.build/CMakeFiles/CMakeOutput.log".
triqs@0cbe525fa271:/home/environments/maxent.build$ cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
triqs@0cbe525fa271:/home/environments/maxent.build$ 

```

thank you.

**Comment by the-hampel** [comment]
Hi,

I would assume, that this problem occurs, because triqs is actually not compiled in the container, but rather installed via ubuntu package manager. Therefore, the container image does not need the correct cmake environment. This explains, why you cannot just simply cmake maxent in the container image. However, in principle you could install the correct cmake version in the container and then install maxent, but I am not sure if there are more problems occurring... You can give it a try. @Wentzell Maybe maxent could be included by default in the triqs docker images? 

I would suggest either install maxent locally outside the container, or use an container image with maxent included. See for example https://hub.docker.com/r/materialstheory/triqs . This one is maintained by me. However I am not always using the latest triqs version, but rather the stable releases. So this container is running triqs 2.1 . 

Best,
Alex

**Comment by Wentzell** [comment]
Hi @muhammadgaffar,

Installing maxent into the docker container should be no problem.
You just have to make sure that you use the same compiler that was used for the compilation of triqs. This information is contained in the `TRIQSConfig.cmake` file:

```
$ cat /usr/lib/cmake/triqs/TRIQSConfig.cmake | grep CXX_COMPILER

set(TRIQS_CXX_COMPILER /usr/bin/g++)
```

If you install maxent you should thus configure using

```
CXX=/usr/bin/g++ cmake ../
```

followed by a 

```
sudo make install
```

Let me know if that works for you!

@the-hampel 

I agree that maxent should be and included with the docker image. We will look into this!
Note that our docker container is based on the ubuntu packages which
are always using the latest **stable** version of triqs and its applications.

**Comment by ghost** [comment]
It's working now. Thanks a lot @Wentzell .

Ya i hope triqs docker image contains all triqs features. 

Best all of you!
