### ISSUE TITLE
SP calculation

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/dft_tools#155]
Dear all
Hi
I want to use the LDA+DMFT method for calculation of electronic structure(for example density of states and ...) of "Tb " compound using triqs 3.0.0 and WIEN2k codes.
my calculations are in two step:1) considering spin-polarized interaction without spin-orbit couplings and 2) considering spin-polarized + spin-orbit coupling. I want to do these calculations using full charge self consistency DFT+DMFT. Is here anyone who can help me to knowing the difference between these calculations and help me to knowing which lines should be inserted/deleted in my "case.py " file. I used "Sr2MgOsO6_SOC.py" from triqs website for my compound . Is this true for my both  calculation? 
anothe question is that :why in your tutorial you say that this script is only for nonmagnetic calculation ? I want used this script for ferromagnetic compound using "up" in the "lstart" step of WieN2k calculation.
Sincerely yours 
Reyhaneh

**Comment by the-hampel** [comment]
Hi, 
In general I would say that spin-polarized and SOC calculations are quite advanced. Hence, the number of tutorials is limited here for a good reason. SOC calculations can be done, and as you mentioned this is documented in some tutorials on our webpage. I would suggest to start from there. Than in a second step, if those paramagnetic calculations with SOC are well converged, you can lift the spin-degeneracy in DMFT allowing for magnetic order. First with simple one-shot calculations, then with CSC. 

You are asking for spin-polarized DFT calculations if I understand correctly? However, in general I would suggest to always keep the DFT calculation non-magnetic, and only allow in DMFT for magnetic order. This is much more reasonable as you would expect your main magnetic moments to be created by the localized orbitals you want to treat in DMFT. The problem is that the spin-polarized LDA functional is quite different from the non-magnetic one, and cause serious troubles for the charge self-consistency. For the specifics in Wien2k I cannot directly help you, but this is the reason why in the tutorial for Wien2k no spin-polarization is considered.

**Comment by Reyhanehe** [comment]
Dear Hampel
Thanks a lot for your best and helpful answer to me.
I should read and think more because I still can not understand how we can seperately plot DOS  for both spin-up and spin-down using DFT+DMFT method. can you please explain more about this subject for me?
Bests,
Reyhaneh

**Comment by the-hampel** [comment]
Hi,
Did you already perform spin-polarized calculations within DMFT? You need to remove the up/down equivalent orbitals from the property `deg_shells` in Sumk. Then no spin averaging is performed. Afterwards your local impurity Greens function should show clear difference in occupation of up and down channels. If you use this Greens function as input for Maxent the resulting A(w) should be quite different for up / down. 

Best,
Alex

**Comment by Reyhanehe** [comment]
Dear Hampel
Tahnks a lot
I perfom spin-polarized calculation only for HubbardI method for rare-earth compounds. In this method I add following lines to my "case.py" and plot DOS for both spin-up and spin-down.

`f=open(LDAFilename+'.qdmftup','a')
f.write("%.16f\n"%(correnerg*0.5))
f.close()
f=open(LDAFilename+'.qdmftdn','a')
f.write("%.16f\n"%(correnerg*0.5))
f.close()`

 But now I want to perform this calculation using dft-tools.
Best regards,
Reyhaneh

**Comment by the-hampel** [comment]
Hi, 
Sorry I can not give you a more clear advice at this point. I cannot explain all the steps necessary here. You can have a look for example at our code soliDMFT on github, were we allow for magnetic calculations in DMFT. You have to lift the spin degeneracy in SumK, then it works automatically. Try the following right after you created your Sumk object:
```
SK.deg_shells = []
```
This will lift all degeneracies. Then perform a normal DMFT calculation with your script. Afterwards just plot G_iw with the `oplot` tools in triqs and you should see a difference in the up / down solutions. 

Unfortunately I cannot help you more with this. In future we might have an tutorial on this, but right now we have no further documentation on this issue.

**Comment by Reyhanehe** [comment]
Dear Hampel
Thank you so much for your best comments and your kindly attention to my issue .
So In this time, I should work in detail using triqs code to solve my problem.
With warmest regards,
Reyhaneh
