### ISSUE TITLE
qsub running

### ISSUE THREAD

**Issue by viridibang** [TRIQS/dft_tools#165]
Hi.
I try to perform CSC DFT+DMFT calculation with the VASP 5.4.4.
I'm using the cluster system, thus I need to submit the job using qsub command.
If you don't mind, could you tell me how to make a suitable job.sh file for running the vasp_dmft?

job.sh file for the normal VASP calculation is as below.

#!/bin/bash
#$ -V
#$ -cwd
#$ -N b
#$ -pe mpi 40
#$ -q all.q
#$ -R yes
mpirun  /opt/vasp/vasp.5.4.4.pl2/bin/vasp_std  > vasp.log

**Comment by the-hampel** [comment]
Hi @viridibang,

that is not trivial and depends on your mpi environment. One suggestion is included in dft_tools: https://triqs.github.io/dft_tools/unstable/tutorials/nio_csc.html#charge-self-consistent-dmft on the bottom via the bash script vasp_dmft.sh: https://triqs.github.io/dft_tools/unstable/tutorials/nio_csc.html#charge-self-consistent-dmft . It sits in your triqs installation in the bin dir. This bash script start both Vasp and triqs via bash shell in separate processes. However, this can be problematic, but should definitely work locally. 

A more sophisticated way can be found in soliDMFT: https://github.com/materialstheory/soliDMFT . Check the readme.md file for CSC. Here, vasp etc is started via python subprocesses. You can even define different MPI environments. Check the source code files `vasp_manager.py` and `csc_flow.py` . Let me know if you have any specific questions. 

Best,
Alex

**Comment by viridibang** [comment]
I hope to run CSC DFT+DMFT using the MPI environment, thus, utilizing the soliDMFT might be an alternative way for me.
Could you explain more specifically to perform CSC DFT+DMFT with the soliDMFT?

Best,

**Comment by the-hampel** [comment]
Hi @viridibang,

So where exactly are you stuck? 

Did you successfully adapted Vasp as explained here: https://triqs.github.io/dft_tools/unstable/guide/conv_vasp.html , so that the LOCPROJ file contains the Fermi lvl? 

And locally you should be always able to run the NiO example from the tutorial. Did this work for you? https://triqs.github.io/dft_tools/unstable/guide/dftdmft_selfcons.html#vasp-plovasp  and https://triqs.github.io/dft_tools/unstable/tutorials/nio_csc.html#charge-self-consistent-dmft

If you want to use soliDMFT and have specific questions / problems please open an issue on the github site there.

**Comment by the-hampel** [comment]
Is this still an open issue @viridibang? Otherwise I will close it in the coming days.
