### ISSUE TITLE
UserWarning: Block up maximum difference

### ISSUE THREAD

**Issue by ZhijieFan** [TRIQS/dft_tools#175]
Hi,

I am working on a DFT+DMFT calculation on FeSb2 using Wanner90+TRIQS. All 5 d-orbitals of Fe atoms are considered correlated, but I use a diagonal approximation to calculate only the diagonal terms of the self-energy.
After the first run, I encountered some warning messages:

UserWarning: Block down maximum difference:
{'up_0': array([[0.+0.j]]), 'up_3': array([[0.+0.j]]), 'up_4': array([[0.+0.j]]), 'up_1': array([[0.+0.j]]), 'up_2': array([[0.+0.j]]), 'down_0': array([[0.34900767-2.40741243e-35j]]), 'down_3': array([[0.4427552-7.70371978e-34j]]), 'down_4': array([[-0.05902882+3.00926554e-35j]]), 'down_1': array([[0.08508393+4.81482486e-35j]]), 'down_2': array([[0.02318781-7.8240904e-35j]])}
  warn('Block {} maximum difference:\n'.format(name) + str(maxdiff))

I tried to understand this warning, but I cannot find it in the documents. I wonder what does this warning means? How should I resolve this?

Best,
Zhijie

**Comment by aichhorn** [comment]
Hi, 

I guess you are also doing rotations of the basis system, right? 

In that case, you should get these warnings at the point where you calculate the new local Greens function. The reason is the following: 
1) You start from the original DFT-derived basis set
2) You rotate into a local basis set (due to your solver, etc.)
3) You restrict this new basis to diagonal elements only.
What the code is doing is to formally rotate the object with only diagonal entries back to the original basis set, and checks the 'maximum difference' with the original object. This is what you see here.

It can tell you how much of an error your diagonal approximation produces, but the information of this warning is not very talkative. If you are confident that your diagonal approximation is enough, you can switch this warning off by the option
extract_G_loc(show_warnings=False)
when calculating the local Greens function.

**Comment by the-hampel** [comment]
Is this issue still actively a problem @ZhijieFan ? Otherwise I will close it next week. Feel welcome to open a new issue at any time.
