### ISSUE TITLE
Different types for Gf and Gf.mesh

### ISSUE THREAD

**Issue by LeoGaspard** [TRIQS/dft_tools#219]
Hi, 

I noticed that when using iw_or_w = 'w', the function [extract_g_loc](https://triqs.github.io/dft_tools/latest/_python_api/triqs_dft_tools.sumk_dft.SumkDFT.extract_G_loc.html?highlight=extract_g_loc#triqs_dft_tools.sumk_dft.SumkDFT.extract_G_loc) from the [SumkDFT](https://triqs.github.io/dft_tools/latest/_python_api/triqs_dft_tools.sumk_dft.SumkDFT.html?highlight=sumkdft#triqs_dft_tools.sumk_dft.SumkDFT) object can return a Green's function object that has a mesh type different from the Green's function type.

Here's a minimal example that should produce an output (using any .h5 file generated with Wannier90Converter) 

```
from triqs_dft_tools.sumk_dft import *
from triqs.gf import *

SK = SumkDFT( hdf_file = "SrVO3.h5" )
S = GfReFreq( indices=[0, 1, 2] , window=(-5, 2), n_points=1000)
Sigma = BlockGf( name_list = ('up', 'down'), block_list = (S, S), make_copies=True, name='Sigma')
SK.put_Sigma( [Sigma] )

G = SK.extract_G_loc(iw_or_w='w', broadening=0)[0]

print( type( G['up'] ) )
print( type (G['up'].mesh) )
```

Output : 
```
<class 'triqs.gf.backwd_compat.gf_imfreq.GfImFreq'>
<class 'triqs.gf.meshes.MeshReFreq'>
```

It seems that it comes from the call to the [create_gf](https://triqs.github.io/dft_tools/latest/_python_api/triqs_dft_tools.block_structure.BlockStructure.create_gf.html#triqs_dft_tools.block_structure.BlockStructure.create_gf) that is made in [transform_to_solver_blocks](https://triqs.github.io/dft_tools/latest/_python_api/triqs_dft_tools.block_structure.BlockStructure.create_gf.html#triqs_dft_tools.block_structure.BlockStructure.create_gf) : 

```
 G_out = [self.block_structure.create_gf(ish=ish, mesh=G_loc[self.inequiv_to_corr[ish]].mesh)
                     for ish in range(self.n_inequiv_shells)]
```
In this call, the Gf type is not specified and is then GfImFreq, whereas the mesh can be something else (MeshReFreq in the example). 

I am using version 3.1.0 

Best,
Léo

**Comment by the-hampel** [comment]
Hi @LeoGaspard , 
thank you fore reporting this behavior. Because, of these weird behaviors of the sumk object we did a major rework of how the `mesh` is dealt with in the whole class on the unstable branch, which is not yet released. This weird behavior can only avoided currently by using `sumk.put_sigma` first, with a `sigma` Gf container having the correct mesh you want to use also later when calling `extract_G_loc`. 

This behavior is very confusing and in the unstable branch the `sumk` class takes as a init parameter a Gf mesh to define the mesh of the sumk object once and for all. Only certain functions allow to be evaluated on a different mesh in the new version. However, since the new version is braking backward compatibility with scripts we cannot merge the fixes simply on the current release. The new version of dfttools would throw an (catched) error: 
```
ValueError: put_Sigma: Sigma_imp must have the same mesh as SumKDFT.mesh.
```
Feel free to test the unstable version of dfttools. The new version takes either a mesh upon construction, or assumes as default a beta=40 MeshImFreq. Also I am not sure how to fix this problem in the current release. I could also throw an exception if the mesh of Sigma does not match the choice of `iw_or_w` .

**Comment by the-hampel** [comment]
Additionally, I find this behavior of the base library very confusing that you reported. This should be fixed in triqs maybe? In the current version one can feed a `MeshReFreq` mesh into a `GfImFreq` init:
```
from triqs.gf import *

mesh = MeshReFreq(window=(-5,5), n_w=1001)
Gw = GfImFreq(mesh=mesh, target_shape=[1,1])
print(Gw)
print(Gw.mesh)
```
gives:
```
Greens Function  with mesh Real Freq Mesh of size 1001, omega_min: -5, omega_max: 5 and target_shape (1, 1): 

Real Freq Mesh of size 1001, omega_min: -5, omega_max: 5
```
which makes no sense. It correctly decides to create a Gf on a MeshReFreq, but this should maybe trhow an error? @Wentzell can you comment / take a look? I know the `GfImFreq` init of a Gf is depracted soon, but right now this leads to funny behavior, which we should fix? What do you think?

**Comment by LeoGaspard** [comment]
Hi, 
Thank you very much for your answer. I will try to use the unstable version of DFTTools and be extra careful that the mesh of the Green's functions that I use is always consistent with their types

**Comment by Wentzell** [comment]
Dear @LeoGaspard @the-hampel,

Thank you for pointing out this inconsistency.
I have addressed this in the development branch of TRIQS, where we are now checking that the mesh type is compatible. C.f. https://github.com/TRIQS/triqs/commit/a42f076547196848aecde783ce4529d45ec15298
