### ISSUE TITLE
Questions about DC

### ISSUE THREAD

**Issue by gsclauzero** [TRIQS/dft_tools#58]
Hi,
    this is not really an issue, I just would like to understand the idea behind the instruction
 
   S.Sigma_iw << SK.dc_imp[0]['up'][0,0]

in the one-shot DFT+DMFT example on the website at https://triqs.ipht.cnrs.fr/1.4/applications/dft_tools/guide/dftdmft_singleshot.html#a-full-dft-dmft-calculation

If I understand correctly, SK.dc_imp has the same block structure of Sigma_iw, but the latter is also frequency dependent. So, will this instruction initialize the Sigma_iw blocks' elements with a constant?
Why do you write SK.dc_imp[0]['up'][0,0], rather then SK.dc_imp[0] ? Is it a C-kind-of instruction, where you can specify the address of the first elements to point to the array?

I also have another question. I would like to disable DC for testing purposes. Would it be enough to comment the lines with calc_dc in the script? I guess that imp_dc is initialized with zeros, so in practice nothing changes when add_dc is called. Or am I mistaken?

Thanks, GS

BTW, is this the right place for this kind of discussion?

**Comment by aichhorn** [comment]
Hi,
The idea behind this line is indeed to initialise the self energy with a value that is close to its Hartree value. SK.dc_imp[0]['up'][0,0] is just a number (double), and it is put to all the blocks of Sigma as a constant. You can also remove this line, but then convergence of the DMFT SC loop will be much slower.

disabling the DC can normally be done in exactly the way you described it. dc_imp is just a matrix of zeros then throughout the calculation.

**Comment by opeil** [comment]
I guess, the question was what the value of Sigma will be when one does
`Sigma_iw << const`. It actulally filles all blocks with matrices `const *
identity(N)`, where N is the size of a block.

   As far as I know, one cannot do simply `Sigma_iw << SK.dc_imp[0]`
because the dictionary is not allowed in the RHS of this expression. You
would have to do `for ind, s in Sigma_iw: s << SK.dc_imp[0][ind]` in
general. But since most of the time DC is a spin- and orbital-independent
constant self-energy can be initialized by any diagonal value of the DC
matrix.

   To set DC to zero, the easiest (to my taste) is to add to your `calc_dc`
function a parameter `use_dc_value=0.0`. In this case, the density matrix
is ignored and the value is set to 0.0.

   Hope this helps.

On Tue, Feb 23, 2016 at 12:17 PM, Markus Aichhorn <notifications@github.com>
wrote:

> Hi,
> The idea behind this line is indeed to initialise the self energy with a
> value that is close to its Hartree value. SK.dc_imp[0]['up'][0,0] is just a
> number (double), and it is put to all the blocks of Sigma as a constant.
> You can also remove this line, but then convergence of the DMFT SC loop
> will be much slower.
>
> disabling the DC can normally be done in exactly the way you described it.
> dc_imp is just a matrix of zeros then throughout the calculation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TRIQS/dft_tools/issues/58#issuecomment-187658370>.
>



-- 

 Dr. Oleg E. Peil
 Department of Quantum Matter Physics
 Universite de Geneve
 CH-1211 Geneve 4
 Switzerland                Tel :+41 (0)22 379 3571

**Comment by gsclauzero** [comment]
Thank you Markus and Oleg for your advice.
Just a minor point:
assuming that the block size (let's call it "dim") is larger than one, will the instruction assign the constant SK.dc_imp[0]['up'][0,0] to all dim*dim elements, or just to the dim elements on the diagonal (as Oleg suggests)?
Is there any way (other than experimenting), where I can learn the behaviour of the << operator in such cases?

**Comment by opeil** [comment]
A constant will fill only the diagonal elements. On a technical level,
when `gf << val` is encountered the scalar `val` is transformed to a
descriptor `Const(val)` and the definition of the latter you can see in
`src/pytriqs/gf/local/descriptor_base.py`, lines ~82--100. You can see
there that such an assignment works only for square blocks and in such a
case what is really assigned is `val * numpy.identity(dim)`.

On Wed, Feb 24, 2016 at 11:05 AM, Gabriele Sclauzero <
notifications@github.com> wrote:

> Thank you Markus and Oleg for your advice.
> Just a minor point:
> assuming that the block size (let's call it "dim") is larger than one,
> will the instruction assign the constant SK.dc_imp[0]['up'][0,0] to all
> dim*dim elements, or just to the dim elements on the diagonal (as Oleg
> suggests)?
> Is there any way (other than experimenting), where I can learn the
> behaviour of the << operator in such cases?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TRIQS/dft_tools/issues/58#issuecomment-188173344>.
>



-- 

 Dr. Oleg E. Peil
 Department of Quantum Matter Physics
 Universite de Geneve
 CH-1211 Geneve 4
 Switzerland                Tel :+41 (0)22 379 3571
