### ISSUE TITLE
[sumk_dft] total density calculation is time consuming for large systems

### ISSUE THREAD

**Issue by ywchoi92** [TRIQS/dft_tools#71]
Dear all,
I am trying to do DFT+DMFT calculation with a large system (4 layers of FeSe slab). 
It has ~ 60 atoms and ~380 correlated shell electrons. 

But, SumkDFT.total_density() function, which is needed to find the chemical potential in DMFT run, takes too much time when the Bloch basis set size becomes large. 

I suspect the main bottleneck could be the matrix inversion operations in the lattice Green's function calculation. (i.e. dft_tools/python/sumk_dft.py:line 570 G_latt.invert())

Is there a way to improve the scalability of this kind of computation?

I think a proper way is to parallelize the lattice Green's function calculation over omega, 
but I am not sure it can be implemented at DFT_TOOLS level or modification to TRIQS code layer is needed.

Thanks,
Young-Woo Choe

**Comment by mzingl** [comment]
I'm sorry that this issue was left uncommented for such a long time. I guess nobody had a good idea or a solution to your problem.
I can only tell you that the calculation of the local Green function is parallelized in k, which is usually sufficient. However, as soon as you have less k-points than CPU cores you are right that a parallelization in omega would be better. This is however not so trivial to implement.
I'm closing this issue now, as it is rather old. Please reopen it should it be still relevant/important.

Best,
Manuel
