### ISSUE TITLE
Documentation needs to be updated regarding tail fitting functions

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/dft_tools#78]
The tail fitting has changed in `triqs/unstable` and the documentation needs to be update, in particular 

https://triqs.ipht.cnrs.fr/1.x/applications/dft_tools/guide/SrVO3.html#tail-fit-parameters

This is just a reminder that we have to fix this at some point.

Best, Hugo

**Comment by alexandrub53** [comment]
with help from @HugoStrand  what I used instead was:

if mpi.is_master_node():
 for name, sig in S.Sigma_iw:
    fit_known_moments = TailGf(sig.N1,sig.N2,0,0)
    S.Sigma_iw[name].fit_tail(known_moments=fit_known_moments,  max_moment = 4, n_min = 60, n_max = 140)
S.Sigma_iw = mpi.bcast(S.Sigma_iw)

**Comment by parcollet** [comment]
@mferrero @gkraberger 
What happens with the fit_tail function ?
It has changed, but the dft-tools doc has not been updated ?

**Comment by gkraberger** [comment]
Sorry, I'm not sure if I understand the point here. As far as I know, the `fit_tail` function can be used exactly as it did two years ago as long as you deal with real (in Gtau) Green's function objects. It has just been extended to be able to handle complex (in Gtau) Green's functions, but the implementation has to be fixed (e.g. by merging my pull request). Probably it has been extended and modified for the more general Green's function objects available in unstable, but as far as I know that does not change the behavior for the backward-compatible Green's functions like `GfImFreq` - is this correct?

@HugoStrand, the update that has to be done in the doc concerns the `known_moments`, right? If that's the case, I agree that updating the doc is necessary; however, I think this has been around for quite some time and not just in unstable. 

@alexandrub53, Is the `mpi.is_master_node()` really necessary to make it work (I would have thought it isn't) or just a personal preference?

**Comment by alexandrub53** [comment]
@gkraberger 
The fit tail I used was for a real green's function (otherwise I would have used more parameters for the positive and negative part of the tail). Maybe I'm wrong and I'm using the version I compiled with complex, I'll double check to make sure. The mpi.is_master_node() was necessary in my case, otherwise the cluster gave me a warning about a fork and froze.

**Comment by gkraberger** [comment]
I'm sure you're right that your Gf was real, otherwise the code would not have worked without giving the additional parameters for the negative fit window.

Concerning the fork warning, on the cluster I'm using I've never seen that for tail fits, maybe it has to do with the particular settings of the cluster you're using. I still don't think that it should be required to do the tail fit just on the master node, but we could add somewhere in the doc (of triqs, I guess, not dfttools) that one might have to use `mpi.is_master_node()` depending on the cluster...

**Comment by HugoStrand** [comment]
@gkraberger it seems like the call signature of the `fit_tail` function has changed in `triqs/unstable`

The call as given in the documentation:
```python
Sigma.fit_tail(fit_n_moments = 4, fit_min_n = 60, fit_max_n = 140)
```
does not work since the wrapper requires the keyword arguments to match the c++ function. All of the keyword arguments have now dropped the `fit_` prefix, and the working call looks like:

```python
Sigma.fit_tail(known_moments = GfTail(...), max_moment = 4, n_min = 60, n_max = 140)
```

**Comment by gkraberger** [comment]
I guess this part of the doc was written without ever trying it. As far as I can see it was written in July 2016. I tried to run the code
``Sigma.fit_tail(fit_known_moments = TailGf(1,1,0,0), fit_n_moments = 4, fit_min_n = 60, fit_max_n = 140)``
using an old TRIQS installation I had lying around (778ba8590153db10950a531a73e6b6b42e78bb19 from October 2015) and it gave the error `TypeError: Required argument 'known_moments' (pos 1) not found`.

So, this has nothing to do with unstable, but just with wrong doc.

The keywords fit_n_moments, fit_min_n and fit_max_n are what the CTHYB solver takes for tailfitting, but not fit_tail.

**Comment by mzingl** [comment]
My bad, the dfttools doc is certainly wrong. I'll take care of this. 

It's a bit confusing as one can use fit_tail as
```python
for name, s in Sigma_iw:
    Sigma_iw[name].fit_tail(known_moments = TailGf(len(s.indicesL),len(s.indicesR),0,0), max_moment = 4, n_min = 40, n_max = 160)
```
But there is also the tail_fit function in /pytriqs/gf/local/tools.py, which produces the same result with
```python
Sigma_iw << tail_fit(Sigma_iw, fit_known_moments = None, fit_max_moment = 4, fit_min_n = 40, fit_max_n = 160)[0]
```
Of course, tail_fit also uses fit_tail, but it additionally defines default parameters. I guess the only place where it is used is in the cthyb solver. 
For me the issue is that the naming of the same parameters in cthyb and triqs is inconsistent.

Best,
Manuel

**Comment by mzingl** [comment]
For the doc I went now with the second option, as the parameters (fit_max_moment, fit_min_n, fit_max_n) are also used on the same page during the initialization of the cthyb solver. I think that makes it easier to understand for the user.

Best,
Manuel

**Comment by HugoStrand** [comment]
@mzingl Thank you for looking into this and fixing it! 👍

I am closing this issue now.

However, in the long run we should make `tail_fit` work the same and take the same parameters everywhere. The `cthyb` naming case using `fit_max_moment`, `fit_...`, is a bit unfortunate. But since these parameters are passed together with a lot of other parameters the `fit_` prefix is needed to signal that they are for the `Sigma` tail fit and nothing else.

Best, Hugo
