### ISSUE TITLE
Sigma Compatibility Issue

### ISSUE THREAD

**Issue by alexandrub53** [TRIQS/dft_tools#79]
Using a self-energy obtained from a calculation on my local cluster using the unstable version, I tried to do a tail fit on my laptop (on which I have installed the release version 1.4); the version on my computer did not recognize this new version of sigma as being a self-energy but the version on the cluster did. The solution seems to be to update the version on my laptop as well, but thought it's worth mentioning.

Alex

**Comment by HugoStrand** [comment]
Dear Alexandru,

Thank you for reporting your issue!

I need just a little bit more information from you in order to be able to reproduce your problem. What is the piece of code that broke, and with what error message.

If you can make a minimal example reproducing the problem it is very useful. E.g., if the hdf5 file is not too big maybe just add the hdf5 file and a small script that crashes when trying to read the file?

The easier it is for someone else (of us) to reproduce the problem the more likely it is to be fixed.

Cheers, Hugo

**Comment by mzingl** [comment]
This issue was resolved. 
We try to keep backward compatibility, but of course we can never guarantee that 
data produced with a newer TRIQS version can be still used with an older one.
Best,
Manuel
