### ISSUE TITLE
Crashed Magnetic Ni calculation in DMFT cycle

### ISSUE THREAD

**Issue by AlynJ** [TRIQS/dft_tools#92]
Dear TRIQS developers,

I am attempting to perform a DFT+DMFT calculation (with Wien2k) of magnetic Ni with all of its d orbitals in the DMFT cycle. However, all my attempted calculations crash after the first DMFT loop. I get the following error message:

___solve_status = SolverCore.solve(self, **params_kw)

.. Error .. calling C++ overload 
.. solve() -> void 
.. in implementation of method SolverCore.solve
.. C++ error was : 
.. Triqs runtime error at /panfs/panasas01/phys/aj12959/local/src/triqs/cthyb.src/c++/./qmc_data.hpp : 87

The Delta(tau) block number 0 is not real in tau space
.. Error occurred on node 4

I don't know where I'm going wrong here. Would you please have a look at this? 

I did notice that the charge from the correlated orbital, the total density and total charge from the Impurity problem, output from the dmft cycle, are different. However, I noticed that for SrVO3 these are (approximately) the same. Is this an indication of the error in my Ni calculation?

I’ve used an energy window of -0.5 to 0.6 Ryd for the Wannier projectors in dmftproj. I've also used U=3.0 eV and J=0.9 eV from [1]. I didn't use a tail fit at this stage; I was going to set it up for the subsequent DMFT loops. I also included h=0.1, but it still crashes with the same error with h=0. The other parameters were the same in my python script as the input script for SrVO3 on the tutorial page. 

I’ve attached the input files from dmftproj, the python script, the output file, the error file and the Ni.h5 file. I’m using TRIQS version 1.4.

Please let me know if you have any questions.

Kind regards,

Alyn

[1] – A. Grechnev, I. Di Marco, M. I. Katsnelson, A. I. Lichtenstein, J. Wills, O. Eriksson, Physical Review B, 76(3), 035107 (2007).

[Ni_DMFT_files.zip](https://github.com/TRIQS/dft_tools/files/2030685/Ni_DMFT_files.zip)

**Comment by the-hampel** [comment]
Hi Alyn,
I took a quick look at you output files. The calculation error is known to me and to my knowledge there can be at least two major reasons for this error to appear:

1. If it appears in the first iteration it usually means that your input Wannier states are not converged enough, or some other projection error appeared, or you explicitly want to do a spin-orbit enabled calculation. So you can either set the solver parameter "imag_threshold" higher (https://triqs.ipht.cnrs.fr/applications/cthyb/reference/solve_parameters.html?highlight=imag_threshold) which lets the cthyb solver ignore these imag elements (which I sometimes do, if know why this is the cae) or enable the solver to treat them explicitly (I have no experience on these calculations)
2. If it appears after the first iteration I usually had a convergence issue. So either your number of sweeps could be too low or the tail-fitting could be already in the first iteration quite important to not mess um the **G**.  Did you try a larger amount of sweeps? I never tried 5 band with dens-dens interaction with Ni, but it might be that 1.6 million sweeps is not enough... Probably someone else here could also comment on how many sweeps are reasonable for this problem.

However, I did not check the input from wien2k. Is the number of electrons correct? That the occupation of the impurity is different before and after the first iteration is ok, since your dmft loop is not converged yet and if it does not deviate too much it does not cause any trouble. 

Site note: be careful with the choice of U. I might mix that up, but In the reference that you put they identified U=F^0, where you used instead the kanamori form for the construction of interaction matrix in your dmft script. Therefore, the definition of U might be different and the resulting coulomb matrix as well. 

Best,
Alex

**Comment by aichhorn** [comment]
I have seen a couple of things in your input files. First of all, you did spin-polarised DFT calculations. If using DMFT, we normally start from non-magnetic DFT calculations, and let the magnetism only come in through correlations, i.e. by a splitting of the up and down self energies.
Second, you used complex harmonics in Ni.indmftpr. Maybe you should use 'cubic' instead of 'complex'. This should also remove the small off-diagonal matrix elements in your Wannier basis and give you a much better basis for the local impurity problem for CTHYB.
I think that Alex is right with the convergence issue. A bad Delta in the second iterations normally means that your self energy is just not good enough after the first solution of the impurity problem.

**Comment by AlynJ** [comment]
Thank you for responding so quickly!

After reading Alex's comments, I increased the value of imag_threshold to 1 (which is maybe too high? I tried 1e-6, but it still crashed after the first loop) and included the tail fit (using the same parameters as in the SrVO3 tutorial). The calculation now crashes at the end of the second DMFT loop. This time, there’s a different error message:

RuntimeError:     for name, sig in Sigma_iw: sig.fit_tail(fit_known_moments[name], fit_max_moment, fit_min_n, fit_max_n)

.. Error .. calling C++ overload
.. fit_tail(tail_view known_moments, int max_moment, int n_min, int n_max, bool replace_by_fit) -> void
.. in implementation of method GfImFreq.fit_tail
.. C++ error was :
.. Triqs runtime error at /panfs/panasas01/phys/aj12959/local/src/triqs/triqs.src/triqs/gfs/singularity/fit_tail.cpp : 187

more arguments are needed to fit a complex gf
.. Error occurred on node 1

So now there is an issue with the tail fit. 

I've not tried the calculation for larger sweeps than the number of sweeps I used in the previous calculation. I wanted to use a small number of sweeps to reduce the computation time for these test calculations. The valence charge from Wien2k is 16 as expected. The output from dmftproj doesn’t indicate any projection errors.

Thank you for the heads up for the choice of U. I’ll change the U value to the appropriate form once this issue has been resolved. 

However, I’ve only just read Markus’ comment. I will implement his suggestions and let you know about the results. I’m assuming that I’ll have to use a non zero h value to help the splitting of the up and down self energies?

I am correct in thinking that the spin-polarised DFT calculation inputs are only used for spin-orbit DFT+DMFT calculations? 

I’ve included the Ni.h5 file, the error file and the triqs output file for this attempt.

Kind regards,

Alyn

[attempt2.zip](https://github.com/TRIQS/dft_tools/files/2035198/attempt2.zip)

**Comment by mzingl** [comment]
I have a few comments:

1.) The new error message is misleading.
It is true that the code crashes at the point of the tailfit, but the problem lies not there.
Have a look at your S.G0 or Delta in tau before the first and second iteration. Does it have a tiny imaginary part, which looks like noise? If yes, you might want to force it to 0. We need to fix this in cthyb and dfttools (issue TRIQS/cthyb#83).

2.) Please do not use the parameters of the SrVO3 example blindly for other materials. Have a look at your self-energy and try to find suitable parameters. Messing up the self-energy with a bad tailfit or having too much noise might crash the calculation in the 2nd iteration.

3.) For a magnetic calculation you can also introduce a splitting of up and down on the level of the self-energy before the first iteration (as Markus said).

**Comment by aichhorn** [comment]
Hi again, just one more thing: When using cubic harmonics, all these issues should disappear, since there are no off-diagonals any more that produce the sign problem (and the problems with complex Delta(tau)). Are you using the complex version of the CTHYB solver? I would use the real one, since complex G(tau) are not needed here.

**Comment by mzingl** [comment]
Hi,
it seems that your tail fit parameters are not good. Is the peak at your starting point of the tail fit? Try to play around with the tail fit parameters, I would suggest to start around 7. If the fit is good in the first iteration it is likely to look good also for the later ones. You might need to increase your statistics as well.
Best, Manuel

**Comment by AlynJ** [comment]
Hi everyone,

Apologies for the delayed response, I wanted to get a reasonable calculation of Ni before posting again.

The fit I did before was poor and I needed to increase the number of sweeps. Below, I’ve attached the imaginary part of the self energy of my Ni calculation in which I did 15 loops of 196000000 sweeps and 5 loops of 420000000 sweeps. I think it still needs more sweeps. The rest of the parameters are the same as before except for the tail fit, which I used the following:

fit_max_moment = 4
fit_min_n = 58
fit_max_n = 80

![ni_self_energy](https://user-images.githubusercontent.com/34216043/41719090-e4b9155a-7556-11e8-8142-fcfeb64f76f4.png)

If there is anything I’m doing wrong here, please let me know. Otherwise, I think this issue can be closed.

Many thanks!

Alyn

**Comment by mzingl** [comment]
Hi Alyn,

tail fit looks good now, you still might want to use more measurements. 
I guess you are showing here the unsymmetrized self-energy. Also have a look at the symmetrized one (after SK.symm_deg_gf). These two should be more similar with increasing number of MC cycles and measurements. The solver input obeys the symmetries, so the output should as well...

Best,
Manuel

**Comment by AlynJ** [comment]
Hi Manuel,

The previous plot was of the unsymmetrized self-energies. I've included the symmetrized plot (from SK.symm_deg_gf) below. There's a small split between the eg and t2g states for each spin. The splitting between the self-energies is most likely due to using the input h_field = 0.1. Am I using an appropriate value of h_field for splitting the self-energies in Ni? If not, what value of h_field should I be using? 

![ni_self_energy_symmetry](https://user-images.githubusercontent.com/34216043/41768464-2e85e5c0-7604-11e8-8687-3fbbf192c63f.png)

Thanks,

Alyn

**Comment by mzingl** [comment]
Hi Alyn,

you can work with the h_field, but I don't have experience with that. I am usually using a splitting in the self-energy, as described in this issue above. 
Further, I realized that you need to be careful with the symmetrization in this case. The up and down spin should not be the same, but with the symmetrization you make them equal in each iteration. So, I would symmetrize those orbitals, which should be equal by hand.

Best,
Manuel

**Comment by AlynJ** [comment]
Hi Manuel,

So is splitting the self-energy as simple as adding/subtracting an initial small constant (only in the first iteration) from each spin self-energy and then continuing iterating until convergence?

Also, to calculate the magnetic moment of this DFT+DMFT Ni, do I calculate it from the local susceptibility? If so, how do I calculate the local susceptibility (i.e. how do I calculate the correlation functions and so on) in TRIQS?

I’m not entirely sure I understand what you mean in the last paragraph of your last message. Am I correct in my understanding that after the symmetrisation of the self-energy, this causes both spin self-energies to be equal to each other? If so, do I have to symmetrise each spin separately (i.e. call upon SK.symm_deg_gf for each spin separately)?

Thanks,

Alyn

**Comment by mzingl** [comment]
Hi Alyn,

yes you can do it in the way as described above by adding/subtracting small constants.

It depends on what you want to calculate/measure, but the ordered magnetic moment would be only the difference of the up and down density.

Yes, initially from the DFT input DFTTool can not know that up and down are not the same anymore. In general, SK.deg_shells tells you which orbitals are being symmetrized. You can either modify this or write a little function where you symmetrize the relevant orbitals by hand.

Best,
Manuel
