### ISSUE TITLE
TRIQS/SRVO3 

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/dft_tools#93]
**Hi all
I want run the dft+dmft calculation for SrVO3 compound using TRIQS code. for my work I use the SrVO3.py such as below:**
import pytriqs.utility.mpi as mpi
from pytriqs.operators.util import *
from pytriqs.archive import HDFArchive
from pytriqs.applications.impurity_solvers.cthyb import *
from pytriqs.gf.local import *
from pytriqs.applications.dft.sumk_dft import *

dft_filename='SrVO3'
U = 4.0
J = 0.65
beta = 40
loops = 15                       # Number of DMFT sc-loops
sigma_mix = 1.0                  # Mixing factor of Sigma after solution of the AIM
delta_mix = 1.0                  # Mixing factor of Delta as input for the AIM
dc_type = 0                      # DC type: 0 FLL, 1 Held, 2 AMF
use_blocks = True                # use bloc structure from DFT input
prec_mu = 0.0001
h_field = 0.0
 Solver parameters
p = {}
p["max_time"] = -1
p["random_seed"] = 123 * mpi.rank + 567
p["length_cycle"] = 200
p["n_warmup_cycles"] = 100000
p["n_cycles"] = 1000000
p["perfrom_tail_fit"] = True
p["fit_max_moments"] = 4
p["fit_min_n"] = 30
p["fit_max_n"] = 60
# If conversion step was not done, we could do it here. Uncomment the lines it you want to do this.
from pytriqs.applications.dft.converters.wien2k_converter import *
Converter = Wien2kConverter(filename=dft_filename, repacking=True)
Converter.convert_dft_input()
mpi.barrier()

previous_runs = 0
previous_present = False
......
.....
.....
.....
....
....
.....
....
.....

# **but when I run "pytriqs SrVO3.py" I receive this error:**
Starting on 1 Nodes at : 2018-05-24 03:00:39.467761
Repacking the file SrVO3.h5
Reading input from SrVO3.ctqmcout...
Traceback (most recent call last):
  File "SrVO3.py", line 35, in <module>
    Converter.convert_dft_input()
 " File "/usr/local/codes/triqs/triqs.install/lib/python2.7/site-packages/pytriqs/applications/dft/converters/wien2k_converter.py", line 255, in convert_dft_input
    raise "Wien2k_converter : reading file %s failed!" % self.dft_file
TypeError: exceptions must be old-style classes or derived from BaseException, not str"

**Comment by Reyhanehe** [comment]
Is there any one how can help me about this error?
thanks a lot

**Comment by mzingl** [comment]
Hi,
you don't have the SrVO3.ctqmcout file in your folder.
Did you perform the Wien2k calculation for SrVO3 and construct the projectors with dmftproj?
Best,
Manuel

(PS: The error message is unclear, I'll change this tomorrow.)

**Comment by Reyhanehe** [comment]
Hi Dear Manuel
yes at first I run a wien2k script such as below :
"runsp_lapw  -so -p...........   "
In the "SrVO3.indmftpr" file I  changed the line "SO" from 0 to 1 for calculation of spin orbit interaction in this compound.
then I run this script:
"x lapw2 -up/dn -c -so -almd -p"
then I use this script:
"dmftproj -sp -so"
finally when I want to run the "pytriqs SrVO3.py" I had an error that I posted it before and I do not know the reason of it.
CAn you help me to solving this problem?
Best,
Reyhaneh

**Comment by aichhorn** [comment]
Why don't you try first without spin polarisation and without spin-orbit coupling to get an easier starting point? What you are doing is quite involved as a first step.

**Comment by mzingl** [comment]
Let me emphasize here that including SO is usually not possible with 'the click of a button'.
Things get complicated and you need to be careful and understand/check each step of your calculation.
I agree to aichhorn that it is absolutely necessary to do SrVO3 without SOC first!
That being said, I have two further remarks:
1.) do not use the -p option in combination with dmftproj. You should run one Wien2k cycle without the -p option before running dmftproj.
2.) As I said above, you get the error because you do not have a case.ctqmcout file in your folder.
This file is written by dmftproj, so I can only guess that dmftproj aborts with an error.
Manuel

**Comment by mzingl** [comment]
Well, what you are showing here is only the calculation of the chemical potential before the first DMFT iteration. This should give you 0.
What you need to do is to run a few DMFT cycles (about 15).
If this is your first DMFT calculation, you should spend time on studying all the quantities which appear in the loop and also study the convergence of these. Look at the self-energy, your Green's function, check the tailfit, understand how the solver behaves with the number of measurement, understand the double counting, and so on....
I have to emphasize that you cannot produce meaningful results by only 'running the scripts' (please see [https://triqs.ipht.cnrs.fr/1.4/applications/dft_tools/basicnotions/first.html](url) for our philosophy).

Concerning SOC, you have two options, you can include it on the DFT level (as you tried), or one can add a SOC term to the Hamiltonian in DMFT. Let me also say that at this point calculations get messy: you have off-diagonal elements in the hybridization and you likely end up with a severe sign problem in CTQMC, especially when the calculations are done in a naive way.
SOC in DFT+DMFT is a current line of research and we are not at the stage where you can include SOC in DFTTools by e.g. simply setting a flag (like it is for most DFT codes).
Due to this reasons we also don't have a user guide for SOC in our documentation.
Manuel

**Comment by Reyhanehe** [comment]
Dear Manuel
thanks for your valuable comment .
you said me that I should not use the "p" swich in my calculations, so It creates another question for me, how we can run in parallel cores with my computer in triqs code?
thanks a lot
Reyhaneh

**Comment by mzingl** [comment]
You can run the Wien2k with -p, but then you should perform one cycle without -p:
x lapw0
x lapw1
x lapw2 -almd

The TRIQS DMFT python script can be run with mpirun -np NCORES pytriqs SrVO3.py
For SrVO3 without SOC I would recommend at least 32 cores for the given parameters to obtain a reasonable accuracy.

As I said above, I admit that our documentation and our current tools for SOC are currently not in the best shape. I'll discuss this with other developers at a meeting in a few weeks.

Best,
Manuel

**Comment by Reyhanehe** [comment]
Dear Manuel
your comments are so useful for me. But I am like to knowing about the SOC calculation too.
It is my pleasure that also you  send your idea about this calculation for me and other triqs user  in this issue.
thank you so much
Reyhaneh

**Comment by mzingl** [comment]
I was wrong, you have a case.ctqmcout file in your folder, but our converter cannot read it.
Without seeing the file itself this is however impossible to know what is going wrong (might be the -p option in Wien2k).

**Comment by Reyhanehe** [comment]
Dear Manuel
When I want to run SOC calculation in my work I did not have the "case.ctqmcount" in my folder, but when I rum without SOC interaction I have it in my folder.
But the speed of this run is so slow, because I use one core in my running ( "run -qdmft 1")and when I use another  expression such as "mpirun" in my work I have the error that this command is not find.

can you help me more for solving this problem becaue I did not understand your last comment about this issue clearly.
thank you
Reyhaneh

**Comment by mzingl** [comment]
You are mixing up things.
1.) The 'run' is for fully charge self-consistent calculations, you don't want to do this at this point.
2.) With one core you won't be able to run a meaningful DFT+DMFT calculation.
2.) You probably don't have mpi installed on your machine.

It seems that you are new to DFT+DMFT. You will need to go through the TRIQS tutorials (TRIQS/tutorials on github) and the TRIQS, the TRIQS/cthyb, and the TRIQS/DFTTools user guide step by step!
I'm sorry, but teaching the use of our package is not the purpose of a github issues.

**Comment by Reyhanehe** [comment]
Dear Manuel
Thank you very much 
I will read more than before about triqs and its application and programs.
Reyhaneh

**Comment by Reyhanehe** [comment]
**Dear all 
I have another question. When I ran "pytriqs SrVO3.py" without SOC interaction I have the below error.**
Iteration =  1
Dichotomy adjustment of Chemical Potential to obtain Total Density = 19.000000 +/- 0.000100
    Chemical Potential = 0.500000  
    Total Density = 20.217319
    0.000000 < Chemical Potential < 0.500000
    18.993424 < Total Density < 20.217319
    0.002687 < Chemical Potential < 0.500000
    18.996430 < Total Density < 20.217319
    0.004141 < Chemical Potential < 0.500000
    18.998092 < Total Density < 20.217319
    0.004917 < Chemical Potential < 0.500000
    18.998990 < Total Density < 20.217319
    0.005327 < Chemical Potential < 0.500000
    18.999469 < Total Density < 20.217319
    0.005542 < Chemical Potential < 0.500000
    18.999721 < Total Density < 20.217319
    0.005656 < Chemical Potential < 0.500000
    18.999854 < Total Density < 20.217319
    0.005715 < Chemical Potential < 0.500000
    18.999923 < Total Density < 20.217319
    Chemical Potential found in 8 iterations : 
    Total Density = 18.999923;Chemical Potential = 0.005715
Total charge of Gloc : 1.310301
DC for shell 0 and block up = 2.187812
DC for shell 0 and block down = 2.187812
DC energy for shell 0 = 0.548892734476
Traceback (most recent call last):
  File "SrVO33.py", line 117, in <module>
    S.solve(h_int=h_int, **p)
  File "/usr/local/codes/triqs/triqs.install/lib/python2.7/site-packages/pytriqs/applications/impurity_solvers/cthyb/cthyb_solver.py", line 95, in solve
    solve_status = SolverCore.solve(self, **params_kw)
TypeError: 
---- There are 4 errors in Python -> C++ transcription for the class solve_parameters_t

1 The parameter 'fit_min_n' is not recognized.
2 The parameter 'fit_max_moments' is not recognized.
3 The parameter 'perfrom_tail_fit' is not recognized.
4 The parameter 'fit_max_n' is not recognized.


**can you help me for solving it ?
thank you very much
Reyhaneh**
